# basic options
url: https://chakraya.com
title: Welcome to Chakraya Blog
author: Chamara Thilina
email: chamara.thilina.samarakoon@gmail.com
description: Through out the blog I am planning to demostrate/explore specific tasks which involves various technologies.
github_username:  chakraya

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
