# basic options
title: My journey to devops world
author: Chamara Thilina
email: chamara.thilina.samarakoon@gmail.com
description: Through out the blog I am planning to demostrate/explore specific tasks which involves various technologies.
github_username:  chakrya

# Build settings
markdown: kramdown
theme: minima
